<?php


/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a
 * particular render array is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme
 *
 * If you change this method, clear theme registry and routing
 * table 'drush cc theme-registry' and 'drush cc router'.
 */
function parking_theme($existing, $type, $theme, $path) {

    $path = \Drupal::service('extension.list.module')->getPath('parking');
    
  return [
    'departure_template' => [

        // The name of the twig template (departure.html.twig).
        'template' => 'departure',

        // Optionally define path to Twig template files.
        // The directory path of the parking module, so that it doesn't need to be looked up.
        'path' => $path . '/templates',

        // Optionally define variables that will be passed to the Twig
        // template and set default values for them.
        'variables' => [
            'bookid' => '',
            'plateNum' => '',
            'cost' => '',
            'departureform' => '',

        ],

    ],

    'arrival_template' => [
        // The name of the twig template (departure.html.twig).
        'template' => 'arrival',

        // Optionally define path to Twig template files.
        // The directory path of the parking module, so that it doesn't need to be looked up.
        'path' => $path . '/templates',

        // Optionally define variables that will be passed to the Twig
        // template and set default values for them.
        'variables' => [
            'arrivalform' => '',

        ],
    ],

    'dashboard_template' => [
        // The name of the twig template (departure.html.twig).
        'template' => 'dashboard',

        // Optionally define path to Twig template files.
        // The directory path of the parking module, so that it doesn't need to be looked up.
        'path' => $path . '/templates',

        // Optionally define variables that will be passed to the Twig
        // template and set default values for them.
        'variables' => [
            'currentdate' => '',
            'arrivalbutton' => '',
            'departurebutton' => '',
            'occupiedspaces' => '',
            'availablespaces' => '',
            'vehiclelist' => '',
            'perhour' => '',
            'firsthour' => '',
            'unpaidtickets' => '',
            'debtorsview' => '',
            'urlcarlist' => '',
            'urldebtors' => '',
            'configform' => '',
            'change' => '',
            'perday' => '',
            'cache' => '',

        ],
    ],
];
}