<?php

/**
 * @file
 * The parking module file.
 */

/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a
 * particular render array is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme
 *
 * If you change this method, clear theme registry and routing
 * table 'drush cc theme-registry' and 'drush cc router'.
 */
function generate_vehicles_theme($existing, $type, $theme, $path) {

  // Define the to twig files.
  $path = \Drupal::service('extension.list.module')->getPath('generate_vehicles');

  return [
    'generate_vehicles_template' => [

        // The name of the twig template (departure.html.twig).
      'template' => 'generate',

        // Optionally define path to Twig template files.
        // The directory path of the parking module.
        // So that it doesn't need to be looked up.
      'path' => $path . '/templates',

        // Optionally define variables that will be passed to the Twig
        // template and set default values for them.
      'variables' => [
        'generatevehicles' => '',

      ],

    ],

  ];
}
